name: gin-starter

services:
  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./deployments/api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DSN=${DSN}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - JWT_ACCESS_TOKEN__EXPIRES_IN=${JWT_ACCESS_TOKEN__EXPIRES_IN}
      - JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN}
    <<: &default_logging
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
    restart: unless-stopped
    depends_on:
      - postgresql

  postgresql:
    image: postgres:16
    container_name: postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    <<: *default_logging
    restart: unless-stopped

volumes:
  postgres_data:
