[server]
port=8080

[database]
host="127.0.0.1"
port=3306
username="root"
database="go_boilerplate"
password="pass"

[jwt]
secret="djoieDcuhiuqaweDjjD"
access_token_exp_days=1
refresh_token_exp_days=7

[redis]
host="localhost"
port="6379"
database=0
