name: test_and_build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.2'

    - name: Run unit test
      run: make test

    - name: Run go vet
      run: make vet

    - name: Build the application
      run: make build
