name: Build & Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21", "1.22"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
        cache: true

    - name: Unit Test ${{ matrix.go }}
      run: make test

    - name: Go Vet
      run: make vet

    - name: Build
      run: make build
