name: Build & Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18", "1.19"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
        cache: true

    - name: Unit Test ${{ matrix.go }}
      run: make test

    - name: Build
      run: make build_linux
